server:
  port: 8090

spring:
  application:
    name: recherche
  config:
    import: optional:configserver:http://localhost:8888
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 1738
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

excel:
  file:
    path: C:/Users/Amani/Desktop/stage 4eme/amts.xlsx
