spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/stage2024  # Assurez-vous que le port et le nom de la base de données sont corrects
    username: postgres
    password: 1738
    driver-class-name: org.postgresql.Driver

  application:
    name: security
  config:
    import: optional:configserver:http://localhost:8888
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8030

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
